######################################################################
# Automatically generated by qmake (2.01a) Wed Sep 8 16:13:55 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

win32|os2: CONFIG += console
mac:CONFIG -= app_bundle

QT -= core gui

# Input
HEADERS += PlanetWars.h
SOURCES += MyBot.cc PlanetWars.cc
